language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7.5"
  - "7"
before_install: bash test/npm.sh
install:
  - npm i
  - npm link
script:
  - npm run build
  - npm test
cache:
  directories:
    - node_modules
    - /home/travis/.diamond
matrix:
  include:
    - node_js: "8"
      env:
        - CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
    - stage: Babel
      node_js: "7"
      env:
        - ENCRYPTION_LABEL: 614fe36bb44f
        - COMMIT_AUTHOR_EMAIL: hackzzila@gmail.com
      script: bash deploy/deploy.sh