language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
before_install: bash test/npm.sh
install:
  - npm i
  - npm link
cache:
  directories:
    - node_modules
    - /home/travis/.diamond