language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
before_install: bash test/npm.sh
install:
  - npm i
  - npm link
cache:
  directories:
    - node_modules
    - /home/travis/.diamond
matrix:
  include:
    - node_js: "8"
      env:
        - CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8